version: '3.2'

services:
  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  mongo:
    container_name: mongodb
    build:
      context: mongo/
      args:
        MONGO_VERSION: $MONGO_VERSION
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ADMIN_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ADMIN_PASSWORD
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express
    build:
      context: mongo-express/
      args:
        ME_VERSION: $ME_VERSION
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ADMIN_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ADMIN_PASSWORD
      ME_CONFIG_MONGODB_ENABLE_ADMIN: $ME_CONFIG_MONGODB_ENABLE_ADMIN
    ports:
      - "8081:8081"

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
